"use client";

import { useActionState, useEffect, useMemo, useState, useTransition } from "react";
import { MoreHorizontalIcon, PlusIcon } from "lucide-react";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Dialog, DialogClose, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Textarea } from "@/components/ui/textarea";
import { calculateCapacityHours, SPRINT_STATUS_LABELS, WEEKDAYS, workingDaysLabel } from "@/lib/sprint-config";
import { createSprint, deleteSprint, setSprintStatus, updateSprint, type ActionResult } from "../actions";
import type { ProjectOption, SprintRow } from "../types";

type Defaults = { working_days: number[]; daily_work_hours: number };
type FormProps = { mode: "create" | "edit"; sprint?: SprintRow; projects: ProjectOption[]; defaults: Defaults; open: boolean; onOpenChange: (open: boolean) => void };

function SprintFormDialog({ mode, sprint, projects, defaults, open, onOpenChange }: FormProps) {
  const action = mode === "create" ? createSprint : updateSprint;
  const [state, formAction, pending] = useActionState<ActionResult | null, FormData>(action, null);
  const [projectId, setProjectId] = useState(sprint?.project_id ?? projects.find((project) => project.status === "active")?.id ?? "");
  const [workingDays, setWorkingDays] = useState<number[]>(sprint?.working_days ?? defaults.working_days);
  const [startDate, setStartDate] = useState(sprint?.start_date ?? ""); const [endDate, setEndDate] = useState(sprint?.end_date ?? ""); const [dailyHours, setDailyHours] = useState(String(sprint?.daily_work_hours ?? defaults.daily_work_hours));
  const capacity = calculateCapacityHours(startDate, endDate, workingDays, Number(dailyHours));
  useEffect(() => { if (state?.ok) onOpenChange(false); }, [state, onOpenChange]);
  const toggleDay = (day: number, checked: boolean) => setWorkingDays((current) => checked ? [...new Set([...current, day])].sort((a, b) => a - b) : current.filter((value) => value !== day));
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[calc(100%-2rem)] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>{mode === "create" ? "Create sprint" : "Edit sprint"}</DialogTitle><DialogDescription>{mode === "create" ? "The workspace calendar pre-fills this sprint and is saved as its own snapshot." : "Completed sprints cannot be changed."}</DialogDescription></DialogHeader><form action={formAction} className="space-y-4">{sprint ? <input type="hidden" name="id" value={sprint.id} /> : null}<input type="hidden" name="project_id" value={projectId} /><input type="hidden" name="working_days" value={workingDays.join(",")} />
    <div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label htmlFor="sprint-project">Project</Label><Select value={projectId} onValueChange={(value) => setProjectId(value ?? "")}><SelectTrigger id="sprint-project" className="w-full"><SelectValue>{(value) => projects.find((project) => project.id === value)?.name ?? "Select project"}</SelectValue></SelectTrigger><SelectContent>{projects.map((project) => <SelectItem key={project.id} value={project.id}>{project.name}{project.status === "archived" ? " (archived)" : ""}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label htmlFor="sprint-number">Sprint number</Label><Input id="sprint-number" name="sprint_number" type="number" min={1} step={1} required defaultValue={sprint?.sprint_number} placeholder="1" /></div><div className="space-y-2"><Label htmlFor="sprint-version">Version</Label><Input id="sprint-version" name="version" maxLength={80} required defaultValue={sprint?.version ?? ""} placeholder="v1.0" /></div><div className="space-y-2"><Label htmlFor="sprint-name">Sprint name</Label><Input id="sprint-name" name="name" maxLength={160} required defaultValue={sprint?.name ?? ""} placeholder="Foundation" /></div><div className="space-y-2"><Label htmlFor="start-date">Start date</Label><Input id="start-date" name="start_date" type="date" required value={startDate} onChange={(event) => setStartDate(event.target.value)} /></div><div className="space-y-2"><Label htmlFor="end-date">End date</Label><Input id="end-date" name="end_date" type="date" required value={endDate} onChange={(event) => setEndDate(event.target.value)} /></div></div>
    <div className="space-y-2"><Label htmlFor="sprint-description">Description</Label><Textarea id="sprint-description" name="description" maxLength={2000} defaultValue={sprint?.description ?? ""} placeholder="Goals and scope for this sprint" /></div>
    <fieldset className="space-y-2"><legend className="text-sm font-medium">Working days</legend><div className="flex flex-wrap gap-x-4 gap-y-2">{WEEKDAYS.map((day) => <label className="flex items-center gap-2 text-sm" key={day.value}><Checkbox checked={workingDays.includes(day.value)} onCheckedChange={(checked) => toggleDay(day.value, checked)} /><span>{day.shortLabel}</span></label>)}</div></fieldset>
    <div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label htmlFor="daily-hours">Hours per working day</Label><Input id="daily-hours" name="daily_work_hours" type="number" min="0.25" max="24" step="0.25" required value={dailyHours} onChange={(event) => setDailyHours(event.target.value)} /></div><div className="rounded-2xl border bg-muted/40 px-3 py-2"><p className="text-xs text-muted-foreground">Planned capacity</p><p className="text-lg font-semibold">{capacity.toLocaleString("en", { maximumFractionDigits: 2 })} hours</p></div></div>
    {state && !state.ok ? <Alert variant="destructive"><AlertDescription>{state.error}</AlertDescription></Alert> : null}<DialogFooter><DialogClose render={<Button type="button" variant="outline" />}>Cancel</DialogClose><Button type="submit" disabled={pending || !projectId || workingDays.length === 0}>{pending ? "Saving…" : mode === "create" ? "Create sprint" : "Save changes"}</Button></DialogFooter>
  </form></DialogContent></Dialog>;
}

export function SprintManager({ projects, sprints, defaults }: { projects: ProjectOption[]; sprints: SprintRow[]; defaults: Defaults }) {
  const [creating, setCreating] = useState(false); const [editing, setEditing] = useState<SprintRow | null>(null); const [deleting, setDeleting] = useState<SprintRow | null>(null); const [error, setError] = useState<string | null>(null); const [pending, startTransition] = useTransition();
  const projectNames = useMemo(() => new Map(projects.map((project) => [project.id, project.name])), [projects]); const activeProjects = projects.filter((project) => project.status === "active");
  const run = (work: () => Promise<ActionResult>) => startTransition(async () => { const result = await work(); if (!result.ok) setError(result.error); else setDeleting(null); });
  return <div className="space-y-4"><div className="flex items-center justify-between gap-4"><p className="text-sm text-muted-foreground">{sprints.length} {sprints.length === 1 ? "sprint" : "sprints"}</p><Button disabled={activeProjects.length === 0} onClick={() => setCreating(true)}><PlusIcon data-icon="inline-start" />Create sprint</Button></div>{activeProjects.length === 0 ? <Alert><AlertDescription>Create or unarchive an active project before creating a sprint.</AlertDescription></Alert> : null}{error ? <Alert variant="destructive"><AlertDescription>{error}</AlertDescription></Alert> : null}
    <div className="overflow-x-auto rounded-2xl border"><Table><TableHeader><TableRow><TableHead>Sprint</TableHead><TableHead>Project</TableHead><TableHead>Dates</TableHead><TableHead>Capacity</TableHead><TableHead>Status</TableHead><TableHead className="w-0" /></TableRow></TableHeader><TableBody>{sprints.map((sprint) => <TableRow key={sprint.id}><TableCell><p className="font-medium">#{sprint.sprint_number} · {sprint.name}</p><p className="text-xs text-muted-foreground">{sprint.version}{sprint.description ? ` · ${sprint.description}` : ""}</p></TableCell><TableCell>{projectNames.get(sprint.project_id) ?? "Unknown project"}</TableCell><TableCell className="text-muted-foreground">{sprint.start_date} — {sprint.end_date}<p className="text-xs">{workingDaysLabel(sprint.working_days)} · {sprint.daily_work_hours}h/day</p></TableCell><TableCell>{Number(sprint.planned_capacity_hours).toLocaleString("en", { maximumFractionDigits: 2 })}h</TableCell><TableCell><Badge variant={sprint.status === "active" ? "default" : sprint.status === "completed" ? "secondary" : "outline"}>{SPRINT_STATUS_LABELS[sprint.status as keyof typeof SPRINT_STATUS_LABELS] ?? sprint.status}</Badge></TableCell><TableCell><DropdownMenu><DropdownMenuTrigger render={<Button variant="ghost" size="icon-sm" disabled={pending} />}><MoreHorizontalIcon /><span className="sr-only">Actions for sprint {sprint.name}</span></DropdownMenuTrigger><DropdownMenuContent align="end">{sprint.status !== "completed" ? <DropdownMenuItem onClick={() => setEditing(sprint)}>Edit</DropdownMenuItem> : null}{sprint.status === "draft" ? <DropdownMenuItem onClick={() => run(() => setSprintStatus(sprint.id, "active"))}>Start sprint</DropdownMenuItem> : null}{sprint.status === "active" ? <DropdownMenuItem onClick={() => run(() => setSprintStatus(sprint.id, "completed"))}>Complete sprint</DropdownMenuItem> : null}{sprint.status === "draft" ? <><DropdownMenuSeparator /><DropdownMenuItem variant="destructive" onClick={() => setDeleting(sprint)}>Delete</DropdownMenuItem></> : null}</DropdownMenuContent></DropdownMenu></TableCell></TableRow>)}</TableBody></Table></div>
    {creating ? <SprintFormDialog mode="create" projects={projects} defaults={defaults} open onOpenChange={setCreating} /> : null}{editing ? <SprintFormDialog mode="edit" sprint={editing} projects={projects} defaults={defaults} open onOpenChange={(open) => { if (!open) setEditing(null); }} /> : null}<Dialog open={Boolean(deleting)} onOpenChange={(open) => { if (!open) setDeleting(null); }}><DialogContent><DialogHeader><DialogTitle>Delete {deleting?.name}?</DialogTitle><DialogDescription>Only draft sprints can be permanently deleted.</DialogDescription></DialogHeader><DialogFooter><DialogClose render={<Button variant="outline" />}>Cancel</DialogClose><Button variant="destructive" disabled={pending} onClick={() => deleting && run(() => deleteSprint(deleting.id))}>{pending ? "Deleting…" : "Delete sprint"}</Button></DialogFooter></DialogContent></Dialog>
  </div>;
}
